name: Pull Requests

on:
  pull_request:
    branches:
      - main

# TODO: Remove when #8 closes
jobs:
  pull-request:
    name: PR
    uses: canonical/observability/.github/workflows/charm-pull-request.yaml@istio-test
    secrets: inherit
